### ISSUE TITLE
Aqui debe ir la practica de prototipo

### ISSUE THREAD

**Issue by josealfredo79** [SistemasTecTlaxiaco/practicaprototipos-topicos4yan#2]

**Comment by josealfredo79** [comment]
Aqui debe ir la calificación y trabajo...

**Comment by josealfredo79** [comment]
Falta la calificacion y lo voy recoerdando como mas de 4 veces y tambien la practica

**Comment by josealfredo79** [comment]
Nuevamente indico que aquí debe ir la practica y la calificación

**Comment by Yareli-Perez** [comment]
[Uploading practica 1 prototipo de interfaz grafica.pdf…]()

**Comment by OFELHER93** [comment]
Calificación 80 = 16%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
